---
- name: Test Connection and Setup
  hosts: all
  become: true

  tasks:
    - name: Ping all servers
      ping:

    - name: Install Git (just for test)
      apt:
        name: git
        state: present
        update_cache: yes
