vms:
  children:
    webservers:
    loadbalancers:
    databases:
  
  vars:
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3.12

webservers:
  hosts:
    192.168.0.11:
    192.168.0.12:

loadbalancers:
  hosts:
    192.168.0.10:

databases:
  hosts:
    192.168.0.13: