vms:
  children:
    webservers:
    loadbalancer:
    database:
  
  vars:
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3.12

webservers:
  hosts:
    192.168.0.11:
    192.168.0.12:

loadbalancer:
  hosts:
    192.168.0.10:

database:
  hosts:
    192.168.0.13: