vms:
  children:
    webservers:
    loadbalancers:
    databases:
  
  vars:
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3.12

webservers:
  hosts:
    192.168.0.11:
      ansible_ssh_private_key_file: id_rsa
    192.168.0.12:
      ansible_ssh_private_key_file: id_rsa

loadbalancers:
  hosts:
    192.168.0.10:
      ansible_ssh_private_key_file: id_rsa

databases:
  hosts:
    192.168.0.13:
      ansible_ssh_private_key_file: id_rsa